# Basic Python

## 1. Split this string

In [ ]:
s = "Hi there Sam!"

In [ ]:
s.split()

['Hi', 'there', 'Sam!']

## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.

In [ ]:
planet = "Earth"
diameter = 12742

In [ ]:
print('the diameter of {} is {} kilometer.'.format(planet,diameter))

the diameter of Earth is 12742 kilometer.


## 3. In this nest dictionary grab the word "hello"

In [ ]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

In [ ]:
d.get('k1')
[1,
 2,
 3,
 {'tricky':['oh', 'man', 'incetion',{'target':[1, 2, 3, 'hello']}]}]
 

[1,
 2,
 3,
 {'tricky': ['oh', 'man', 'incetion', {'target': [1, 2, 3, 'hello']}]}]

# Numpy

In [ ]:
import numpy as np

## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?

In [ ]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
np.ones(10)*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

## 5. Create an array of all the even integers from 20 to 35

In [ ]:
np.arange(20,36,2)

array([20, 22, 24, 26, 28, 30, 32, 34])

## 6. Create a 3x3 matrix with values ranging from 0 to 8

In [ ]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

## 7. Concatenate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

In [ ]:
a=np.array([1,2,3])
b=np.array([4,5,6])

In [ ]:
np.concatenate((a,b))

array([1, 2, 3, 4, 5, 6])

# Pandas

## 8. Create a dataframe with 3 rows and 2 columns

In [ ]:
import pandas as pd
data=[['vamsi',10],['mahesh',20],['sai',30]]
a=pd.DataFrame(data,columns=['Name','Age'])
print(a)


     Name  Age
0   vamsi   10
1  mahesh   20
2     sai   30


In [ ]:
[24]

[24]

## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [ ]:
from datetime  import  datetime,timedelta

def date_range(start,end):
  delta=end-start  #as timedelta
  days=[start+timedelta(days=i) for i in range(delta.days+1)]
  return days

  start_date=datetime(2023, 1, 1)
  end_date=datetime(2023, 2, 10)

  print(date_range(start_date,end_date))

## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]

In [ ]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

In [ ]:
lists =[[1, 'aaa', 22],[2, 'bbb', 25],[3, 'ccc', 24]]
df=pd.DataFrame(lists,columns=['Number','FName','Age'])
print(df)

   Number FName  Age
0       1   aaa   22
1       2   bbb   25
2       3   ccc   24
